### ISSUE TITLE
Getting the firmware without compiling everything by own

### ISSUE THREAD

**Issue by heshananupama** [dviejo/stm32joystick_demo#1]
Hi do you have prebuilt firmware file included in the repository. If you do so, that would save a lot of time needed to build everything from scratch. I just needed to access the firmware file so if you could point to the exact file that would be a great help thanks. 

Upon running the commands, there were multiple main.elf files generated. Could I know which is the exact firmware is located? 
The last command make flash says that there is no rule in makefile which is true. Could you help me to resolve this?

**Comment by dviejo** [comment]
Hi heshananupama!
I've re-check instalation steps and everything seems to be ok. I can't help you without console output information. Just be sure you are in the folders you have to be. For example, the first command in step 4 can be replaced by '$ cd ..' assuming that the previous commands you executed were those on step 2.

Nevertheless, I've uploaded the main.elf file to github repo. I hope this will help you anyways.
Cheers

**Comment by heshananupama** [comment]
Thank you I think I messed up with the paths. It does work now. Thanks for your time
